apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: namespace-small
  title: OpenShift Namespace Small Size
  description: Creates an OpenShift Namespace Small. Recommended for Development.
  tags:
    - project
    - namespace
spec:
  owner: group:default/rhdh
  type: project
  parameters:
    - title: Provide Information about the OpenShift Namespace
      required:
        - component_id
      properties:
        component_id:
          title: Namespace
          type: string
          description: Unique name of the namespace
  steps:
    - id: template-gitops-deployment
      name: Generating Deployment Resources
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          component_id: {{ '${{ parameters.component_id }}' }}
          source_repository_gitops: https://github.com/redhat-pe-workshop/developer-self-service-helm-charts.git
          source_repository_path: namespace
          owner: {{ '${{ user.entity.metadata.name }}' }}
          namespace: {{ '${{ parameters.component_id }}' }}
          namespace_size: small
          gitops_namespace: {{ rhdh_gitops_namespace }}
          gitops_project: {{ rhdh_gitops_project }}
          git_host: {{ gitlab_host }}
          git_destination: {{ '${{ user.entity.metadata.name }}' }}/{{ '${{ parameters.component_id }}' }}-gitops
          owner_role: admin
        targetPath: {{ './${{ user.entity.metadata.name }}-${{parameters.component_id}}-gitops' }}

    - id: publish
      name: Publishing to Resource Repository
      action: publish:gitlab
      input:
        repoUrl: "{{ gitlab_host }}?owner={{ '${{ user.entity.metadata.name }}' }}&repo={{ '${{parameters.component_id}}' }}-gitops"
        repoVisibility: public
        defaultBranch: main
        title: gitops resources for {{ '${{ parameters.component_id }}' }}
        description: gitops resources for {{ '${{ parameters.component_id }}' }}
        sourcePath: {{ './${{ user.entity.metadata.name }}-${{parameters.component_id}}-gitops' }}

    - id: create-argocd-resources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: {{ '${{ parameters.component_id }}' }}-bootstrap
        argoInstance: main
        namespace: {{ rhdh_gitops_namespace }}
        repoUrl: https://{{ gitlab_host }}/{{ '${{ user.entity.metadata.name }}' }}/{{ '${{ parameters.component_id }}' }}-gitops.git
        path: 'argocd/'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: {{ '${{ steps.publish.output.repoContentsUrl }}' }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Source Code Repository
        url: {{ '${{ steps.publish.output.remoteUrl }}' }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: {{ '${{ steps.register.output.entityRef }}' }}
