apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    argocd/app-selector: rht-gitops.com/${{ values.gitops_namespace }}=${{values.component_id}}
    backstage.io/kubernetes-id: ${{values.component_id}}
    backstage.io/source-location: url:https://${{values.git_host}}/${{values.git_destination}}
    backstage.io/techdocs-ref: url:https://${{values.git_host}}/${{values.git_destination}}
    gitlab.com/project-slug: ${{values.git_destination}}
  tags:
    - namespace
    - project
  links: []
spec:
  type: project
  lifecycle: development
  owner: user:default/${{ values.owner }}
  providesApis: []
