apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: postgres-15-template
  title: Postgres 15 Database
  description: Deploy a Postgres 15 Database to an existing namespace
  tags:
    - application-components
    - postgres
spec:
  owner: group:default/rhdh
  type: application-capabilities
  parameters:
    - title: Provide Information for Postgres 15 Database
      required:
        - component_id
        - namespace
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          default: my-db
          ui:field: EntityNamePicker
          maxLength: 18
        namespace:
          title: Namespace
          type: string
          description: Namespace to which the Postgres database instance will be deployed
          ui:field: OwnedEntityPicker
          ui:options:
            catalogFilter:
              - spec.type: project
                kind: component
  steps:
    - id: template-gitops-deployment
      name: Generating Deployment Resources
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          component_id: {{ '${{ parameters.component_id }}' }}
          source_repository_gitops: https://github.com/btison/pew-helm-charts.git
          owner: {{ '${{ user.entity.metadata.name }}' }}
          namespace: {{ '${{ parameters.namespace | replace("component:default/", "") }}' }}
          gitops_namespace: {{ rhdh_gitops_namespace }}
          gitops_project: {{ rhdh_gitops_project }}
          git_host: {{ gitlab_host }}
          git_destination: {{ '${{ user.entity.metadata.name }}' }}/{{ '${{ parameters.component_id }}' }}-gitops
        targetPath: {{ './${{ user.entity.metadata.name }}-${{parameters.component_id}}-gitops' }}

    - id: publish
      name: Publishing to Resource Repository
      action: publish:gitlab
      input:
        repoUrl: "{{ gitlab_host }}?owner={{ '${{ user.entity.metadata.name }}' }}&repo={{ '${{parameters.component_id}}' }}-gitops"
        repoVisibility: public
        defaultBranch: main
        title: gitops resources for {{ '${{ parameters.component_id }}' }}
        description: gitops resources for {{ '${{ parameters.component_id }}' }}
        sourcePath: {{ './${{ user.entity.metadata.name }}-${{parameters.component_id}}-gitops' }}

    - id: create-argocd-resources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: {{ '${{ user.entity.metadata.name }}-${{ parameters.component_id }}' }}-bootstrap
        argoInstance: main
        namespace: {{ rhdh_gitops_namespace }}
        repoUrl: https://{{ gitlab_host }}/{{ '${{ user.entity.metadata.name }}' }}/{{ '${{ parameters.component_id }}' }}-gitops.git
        path: 'argocd/'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: {{ '${{ steps.publish.output.repoContentsUrl }}' }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Source Code Repository
        url: {{ '${{ steps.publish.output.remoteUrl }}' }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: {{ '${{ steps.register.output.entityRef }}' }}
